### ISSUE TITLE
WiFi Screen appears and dissapears

### ISSUE THREAD

**Issue by hoerbi1000** [coppermilk/wiener_linien_esp32_monitor#7]
Hi, 

If im trying to Install the current Sketch Version, after uploading the WiFi Screen appears For 1 Sec and Dissappears. No WiFi can be found.

I have installed only the correct Versions of the Libaries mentioned in Source.

If i try to Install the old Version from Folder this is Running without any Problem.

Anyone expirience the Same?

**Comment by coppermilk** [comment]
Try factory reset, maybe some trash values in the memory. 
![2024-05-16 09_36_11-coppermilk_wiener_linien_esp32_monitor_ A script for using a T-Display S3 ESP32S](https://github.com/coppermilk/wiener_linien_esp32_monitor/assets/25866713/f0720569-83c3-4c3a-922b-1f98073d5b0a)
